version: "3.8"
services:
  server:
    build: .
    restart: always
    ports: 
      - 9005:9005
    depends_on :
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/opencollab
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rohan@2803
    # Add a health check to wait for MySQL service to be ready
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysqldb"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork  # Assigning to custom network

  mysqldb:
    image: "mysql:8.0.34"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: opencollab
      MYSQL_ROOT_PASSWORD: Rohan@2803
    networks:
      - mynetwork  # Assigning to custom network

networks:
  mynetwork:  # Defining custom network
